#!/bin/bash

export NODE_PATH=/usr/lib/node_modules

webadmin=/root/webadmin
currentPath=$PWD


if [ $# != 1 ] ; then
    bash echoColor "${0}: The number of parameters must be equal to 1" error;
exit 1;
fi


cd ${webadmin}
forever start activityWeb.js ${1}

if [ $? != 0 ];then
    cd ${currentPath}
    bash echoColor "${0}: can't start activityWeb.js !!!" error;
    exit 1;
else
    cd ${currentPath}
    bash echoColor "${0}: start activityWeb.js Success!" info;
    exit 0;
fi