#!/bin/bash

currentPath=$PWD

jc=$(netstat -an | grep LISTEN | grep 150 | awk '{print $4}' | awk -F ':' '{print $2}' )
jcs=(${jc// /})

for key in ${jcs[*]}
do
log=$key:$(netstat -an | grep -v LISTEN | grep $key | wc -l)
bash $currentPath/echoColor $log info
done

log=$(netstat -an | grep 150 | grep -v LISTEN | wc -l)
bash $currentPath/echoColor "allCount: $log" info

if [ $? != 0 ];then
    exit 1;
else
    exit 0;
fi
